config/routes.rb
Rails.application.routes.draw do
  resources :movies, param: :movie_id, constraints: { movie_id: /\d+/ } do
    resources :posts
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :posts, primary_key: 'movie_id', foreign_key: 'movie_id',dependent: :destroy
  validates :movie_id, uniqueness: true

   def self.search(title)
    require 'uri'
    require 'net/http'
    url = URI.parse URI.encode("https://api.themoviedb.org/3/search/movie?page=1&query=#{title}&language=ja-JA&api_key=30dd6dfe595c6a70ddad14ddc4b58ac5")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request.body = "{}"

    response = http.request(request)
    result = JSON.parse(response.body)
  end

  def self.details(id)
    # require 'uri'
    # require 'net/http'
    # url = URI("https://api.themoviedb.org/3/movie/#{id}?language=ja-JA&api_key=30dd6dfe595c6a70ddad14ddc4b58ac5")

    # http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    # request = Net::HTTP::Get.new(url)
    # request.body = "{}"
    # response = http.request(request)
    # result = JSON.parse(response.body)



    require 'uri'
    require 'net/http'
    require 'json'
    require 'open-uri'

    # uri = URI.parse("https://api.themoviedb.org/3/movie/#{id}?language=ja-JA&api_key=30dd6dfe595c6a70ddad14ddc4b58ac5")
    # http = Net::HTTP.new(uri.host, uri.port)
    # http.use_ssl = uri.scheme === "https"
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    # req = Net::HTTP::Get.new(uri)
    # response = http.request(req)
    # result = JSON.parse(response.body)
    # Movie.create(title:result.title)

    require 'themoviedb-api'
    Tmdb::Api.key("30dd6dfe595c6a70ddad14ddc4b58ac5")
    Tmdb::Api.language("ja")
    result = Tmdb::Movie.detail(id)
    movie = Movie.find_or_create_by(movie_id:result.id,title:result.title)
  end

  def to_param
    movie_id.to_s
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :movie, foreign_key: 'movie_id',primary_key: 'movie_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  def search
    @movies = Movie.search(params[:title])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie_info = Movie.details(params[:movie_id])
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      # @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :image)
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_movie
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to movie_post_path(@movie.movie_id,@post.id)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def set_movie
    @movie = Movie.find_by!(movie_id: params[:movie_movie_id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :movie_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.number_field :genre %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.image %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<h1>映画検索</h1>

<div>
  <%= form_with(method: :get, local: true) do |f| %>
    <%= f.label :title_search,"タイトル" %>
    <%= f.text_field :title %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<br>
<div>
  <% if @movies["results"].blank?%>
    条件に一致する映画はありません
  <% else %>
    <table border="1">
      <tr>
        <th>タイトル</th>
        <th>上映日</th>
        <th>あらすじ</th>
      </tr>
      <% @movies["results"].each do |movie| %>
        <tr>
          <td><%= link_to movie['title'],movie_path(movie['id']) %></td>
          <td><%= movie['release_date'] %></td>
          <td><%= movie['overview'] %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/movies/show.html.erb
<div>
  <%= @movie_info["title"] %>
</div>
<div>
  <%= @movie_info["overview"] %>
</div>
<div>
  <%= link_to "公式サイトリンク",@movie_info["homepage"] %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= post.title %>
<% end %>

app/views/posts/new.html.erb
<%= @movie.title %>
<%= form_with(model:[@movie,@post]) do |f| %>
<%= f.hidden_field :title, value: @movie.title %>
<%= f.hidden_field :movie_id, value: @movie.movie_id %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= @movie.title %>
<%= @post.content %>